<a href="https://colab.research.google.com/github/Renan-Domingues/Learn-PyTorch-in-a-day-Daniel-Bourk/blob/main/00_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

1. The documentation on torch.Tensor: https://pytorch.org/docs/stable/tensors.html#torch-tensor
2. The documentation on torch.cuda: https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics


# 2. Create a random tensor with shape (7, 7).

In [2]:
import torch

X = torch.rand(7, 7)

print(X)

tensor([[0.6056, 0.9435, 0.6844, 0.6094, 0.3766, 0.4023, 0.9807],
        [0.4588, 0.3542, 0.4022, 0.8715, 0.0164, 0.8862, 0.7537],
        [0.8964, 0.5733, 0.4523, 0.0045, 0.1761, 0.2787, 0.3975],
        [0.7459, 0.3777, 0.1982, 0.2559, 0.1557, 0.7410, 0.1623],
        [0.5429, 0.1218, 0.0385, 0.7316, 0.8666, 0.4699, 0.5578],
        [0.2447, 0.5774, 0.1581, 0.1825, 0.8777, 0.8782, 0.7900],
        [0.2484, 0.0936, 0.7916, 0.2173, 0.8033, 0.9722, 0.7782]])


# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
(hint: you may have to transpose the second tensor).


In [3]:
Y = torch.rand(1, 7)

Y = Y.T # Or I could do the transpose in the operation Z = torch.matmul(X, Y.T)

Z = torch.matmul(X, Y)

print(Z)



tensor([[2.7770],
        [2.1436],
        [1.7903],
        [1.7359],
        [1.9818],
        [2.1861],
        [2.4499]])



# 4. Set the random seed to 0 and do 2 & 3 over again.

The output should be:

- (tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))



In [6]:
torch.manual_seed(0)

X = torch.rand(7, 7)

Y = torch.rand(1, 7)

Z = torch.matmul(X, Y.T)

print(Z)

'''
 It's not the same result as the question because Pytorch updated the random
 seed in the new vesion, but is given the same result every time...
 that is the goal
 '''

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


"\n It's not the same result as the question because Pytorch updated the random\n seed in the new vesion, but is given the same result every time... \n that is the goal\n "


# 5.
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

- If there is, set the GPU random seed to 1234.



In [10]:
torch.cuda.manual_seed(1234)


# 6.
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(1234)

X = torch.rand(2, 3) # I could send to device here too: Y = torch.rand(2, 3).to(device)

torch.manual_seed(1234) # I put the random seed again, because just work in the next code

Y = torch.rand(2, 3) # I could do the same thing in the X matrix here too

X = X.to(device)
Y = Y.to(device)

print(X)
print(Y)
print(device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
cuda


# 7.
Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [16]:
Z = torch.matmul(X, Y.T)

print(Z, Z.shape)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0') torch.Size([2, 2])


# 8. Find the maximum and minimum values of the output of 7.

In [17]:
z_max = torch.max(Z)
z_min = torch.min(Z)

print(f'Maximun Value = {z_max}\nMinimun value = {z_min}')


Maximun Value = 0.628727912902832
Minimun value = 0.21611443161964417


# 9. Find the maximum and minimum index values of the output of 7.

In [18]:
i_max = torch.argmax(Z)
i_min = torch.argmin(Z)

print(f'The maximun index valuer is {i_max}\nThe minimun index value is {i_min}')

The maximun index valuer is 3
The minimun index value is 1


# 10.
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [21]:
torch.cuda.manual_seed(7)

X = torch.rand(1, 1, 1, 10)
Y = X.squeeze()

print(X, X.shape)
print(Y, Y.shape)

tensor([[[[0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216,
           0.5247, 0.6688]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247,
        0.6688]) torch.Size([10])
