<a href="https://colab.research.google.com/github/Renan-Domingues/Learn-PyTorch-in-a-day-Daniel-Bourk/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors

### Creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0][0][2]

tensor(3)

In [ ]:
TENSOR[0][2][0]

tensor(7)

In [ ]:
TENSOR[0][2][1]

tensor(8)

### Random Tensor

Why Random Tensors?

the way that many neural networks learn is that they start with tensors full of random numbers and than ajust those random numbers to better represent the data

'Start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers'

In [ ]:
# Create a Random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4942, 0.9192, 0.7978, 0.6897],
        [0.6553, 0.3468, 0.2147, 0.3964],
        [0.5199, 0.5758, 0.7587, 0.5338]])

In [ ]:
random_tensor = torch.rand(4, 5, 8)


tensor([[[0.5901, 0.8184, 0.1717, 0.6450, 0.6880, 0.5433, 0.1278, 0.6055],
         [0.3312, 0.4683, 0.9799, 0.6230, 0.8623, 0.6945, 0.0715, 0.1341],
         [0.3017, 0.0216, 0.7930, 0.4185, 0.1597, 0.6752, 0.5706, 0.0240],
         [0.8229, 0.6661, 0.0972, 0.2062, 0.0744, 0.2574, 0.8114, 0.2865],
         [0.5292, 0.5640, 0.5882, 0.1479, 0.5587, 0.5569, 0.9494, 0.4603]],

        [[0.6832, 0.5900, 0.3022, 0.6621, 0.6821, 0.4532, 0.2518, 0.3229],
         [0.9549, 0.6291, 0.1192, 0.3506, 0.6438, 0.8575, 0.0262, 0.8700],
         [0.3546, 0.3190, 0.3271, 0.7969, 0.6515, 0.9522, 0.0725, 0.7484],
         [0.6242, 0.5942, 0.9591, 0.7381, 0.1513, 0.5557, 0.2264, 0.4891],
         [0.6746, 0.1329, 0.6332, 0.4936, 0.1171, 0.7183, 0.5655, 0.3830]],

        [[0.8549, 0.2146, 0.2816, 0.2417, 0.2521, 0.1156, 0.3647, 0.3436],
         [0.3312, 0.6973, 0.3061, 0.8087, 0.5289, 0.9407, 0.6993, 0.2197],
         [0.3338, 0.8433, 0.8282, 0.8756, 0.0871, 0.9524, 0.9761, 0.5096],
         [0.4154, 0.4

In [ ]:
random_tensor[2][4][2]

tensor(0.4975)

In [ ]:
zeros = torch.zeros(4, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zeros = torch.zeros_like(one_to_ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0] dtype=None, device=None, requires_grad=False)


### Manipulatin tensors (tensors operentions)

In [ ]:

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi


Fri May  5 15:20:45 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'